# Generated by Django 3.1 on 2020-09-23 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200922_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
    ]
